# -*- coding: utf-8 -*-
"""CV lab 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJLh440L92PG4w3vdD7Qqh5QU2LU9tec
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

def show_comparison(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))
  plt.subplot(2,2,1)
  plt.imshow(original,cmap="gray")
  plt.title('Original Grayscale Image')
  plt.axis('off')
  #3x3
  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title('average filter(3x3)')
  plt.axis('off')
  #5x5
  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title('average filter(5x5)')
  plt.axis('off')
  #7x7
  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title('average filter(7x7)')
  plt.axis('off')
  plt.tight_layout()
  plt.show()

img=cv2.imread('/content/images.jpg',0)

if img is None:
  print('Error loading image')
else:
  #define averaging
  blur3=np.ones((3,3),np.float32)/9
  blur5=np.ones((5,5),np.float32)/25
  blur7=np.ones((7,7),np.float32)/49

blur3x3=cv2.filter2D(img,-1,blur3)
blur5x5=cv2.filter2D(img,-1,blur5)
blur7x7=cv2.filter2D(img,-1,blur7)

show_comparison(img,blur3x3,blur5x5,blur7x7)

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Function to apply average filter manually
def average_filter(image, kernel_size):
    rows, cols = image.shape
    print(rows,cols)
    pad = kernel_size // 2
    print(pad)
    # Add padding to the image
    padded = np.pad(image, pad, mode='constant', constant_values=0)

    output = np.zeros((rows, cols), dtype=np.uint8)

    # Apply average filtering
    for i in range(rows):
        for j in range(cols):
            region = padded[i:i+kernel_size, j:j+kernel_size]
            output[i, j] = np.sum(region) / (kernel_size * kernel_size)

    return output

# Read grayscale image
img = cv2.imread('/content/images.jpg', 0)

if img is None:
    print("Error loading image")
else:
    blur3x3 = average_filter(img, 3)
    blur5x5 = average_filter(img, 5)
    blur7x7 = average_filter(img, 7)

    # Display results
    plt.figure(figsize=(12, 10))

    plt.subplot(2, 2, 1)
    plt.imshow(img, cmap='gray')
    plt.title("Original Image")
    plt.axis('off')

    plt.subplot(2, 2, 2)
    plt.imshow(blur3x3, cmap='gray')
    plt.title("Average Filter (3x3)")
    plt.axis('off')

    plt.subplot(2, 2, 3)
    plt.imshow(blur5x5, cmap='gray')
    plt.title("Average Filter (5x5)")
    plt.axis('off')

    plt.subplot(2, 2, 4)
    plt.imshow(blur7x7, cmap='gray')
    plt.title("Average Filter (7x7)")
    plt.axis('off')

    plt.tight_layout()
    plt.show()