# -*- coding: utf-8 -*-
"""CV lab 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJLh440L92PG4w3vdD7Qqh5QU2LU9tec
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
def show_comparision(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title("original grayscale image")
  plt.axis('off')
  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title("Average Filter(3,3)")
  plt.axis('off')
  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title("Average Filter(5,5)")
  plt.axis('off')
  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title("Average Filter(7,7)")
  plt.axis('off')
  plt.tight_layout()
  plt.show()
  img=cv2.imread('/content/CV lab 3.jpg',0)
  if img is None:
    print("Error:Image not found..")
  else:
      kernel_3x3=np.ones((3,3),np.float32)/9
      kernel_5x5=np.ones((5,5),np.float32)/25
      kernel_7x7=np.ones((7,7),np.float32)/49

      blur_3x3=cv2.filter2D(img,-1,kernel_3x3)
      blur_5x5=cv2.filter2D(img,-1,kernel_5x5)
      blur_7x7=cv2.filter2D(img,-1,kernel_7x7)

      show_comparison(img, blur3, blur5, blur7)

import cv2
import matplotlib.pyplot as plt
import numpy as np

def show_comparison(original, blur3, blur5, blur7):
    plt.figure(figsize=(12, 10))

    plt.subplot(2, 2, 1)
    plt.imshow(original, cmap='gray')
    plt.title("Original Grayscale Image")
    plt.axis('off')

    plt.subplot(2, 2, 2)
    plt.imshow(blur3, cmap='gray')
    plt.title("Average Filter (3×3)")
    plt.axis('off')

    plt.subplot(2, 2, 3)
    plt.imshow(blur5, cmap='gray')
    plt.title("Average Filter (5×5)")
    plt.axis('off')

    plt.subplot(2, 2, 4)
    plt.imshow(blur7, cmap='gray')
    plt.title("Average Filter (7×7)")
    plt.axis('off')

    plt.tight_layout()
    plt.show()

img = cv2.imread('/content/modern city', 0)

if img is None:
    print("Error: Image not found.")
else:
    kernel_3x3 = np.ones((3, 3), np.float32) / 9
    kernel_5x5 = np.ones((5, 5), np.float32) / 25
    kernel_7x7 = np.ones((7, 7), np.float32) / 49

    blur3 = cv2.filter2D(img, -1, kernel_3x3)
    blur5 = cv2.filter2D(img, -1, kernel_5x5)
    blur7 = cv2.filter2D(img, -1, kernel_7x7)

    show_comparison(img, blur3, blur5, blur7)